import ApiRefTwoCol from '../components/ui/ApiRefTwoCol';
import PageActions from '../components/ui/PageActions';
import PrivatePreviewBanner from '../components/ui/PrivatePreviewBanner';
import VersionTabBar from '../components/ui/VersionTabBar';

/* ─── Parameters ─────────────────────────────────────────────────────────────── */
const PARAMS_REQUEST = [
  { name: 'zoom', required: true, type: 'integer (path)', desc: 'Zoom level of the tile. 3D landmark tiles are only available at zoom levels 15 and 16.' },
  { name: 'x', required: true, type: 'integer (path)', desc: 'Tile column index on the zoom grid. Valid range: 0 to 2^zoom − 1.' },
  { name: 'y', required: true, type: 'integer (path)', desc: 'Tile row index on the zoom grid. Valid range: 0 to 2^zoom − 1.' },
  { name: 'key', required: true, type: 'string (query)', desc: 'Your TomTom API key. Alternatively, pass as TomTom-Api-Key request header for improved security.' },
  { name: 'apiVersion', type: 'integer (query)', default: '2', desc: 'API version to call. Overrides the TomTom-Api-Version header if set. Current value: 2.' },
];

const PARAMS_HEADERS = [
  { name: 'TomTom-Api-Key', required: true, type: 'string (header)', desc: 'Preferred authentication method. Recommended over the key query parameter for improved security.' },
  { name: 'TomTom-Api-Version', required: true, type: 'integer (header)', desc: 'API version. Current value: 2.' },
  { name: 'If-None-Match', type: 'string (header)', desc: 'Conditional request header. If the tile ETag matches, the server returns 304 Not Modified — saving bandwidth.' },
  { name: 'Accept', type: 'string (header)', values: ['model/gltf-binary'], desc: 'Content type accepted. If not supported the server falls back to the default.' },
  { name: 'Tracking-ID', type: 'string (header)', desc: 'Optional request trace identifier. Must match ^[a-zA-Z0-9-]{1,100}. Replicated in the response if provided.' },
];

const PARAMS_RESPONSE = [
  { name: 'body', type: 'binary (model/gltf-binary)', desc: 'Binary glTF 2.0 (.glb) file containing 3D models for the requested tile area. Georeferenced in EPSG:3857 — no further transformation needed.' },
  { name: 'Content-Type', type: 'response header', desc: 'model/gltf-binary' },
  { name: 'Cache-Control', type: 'response header', desc: 'max-age=<decimal> — tiles are publicly cacheable.' },
  { name: 'ETag', type: 'response header', desc: 'Entity tag for conditional requests. Example: W/"2fdbd61f30456".' },
  { name: 'Tracking-ID', type: 'response header', desc: 'Replicated from the request Tracking-ID header, or auto-generated by the service.' },
];

/* ─── Code examples ──────────────────────────────────────────────────────────── */
const CODE_REQUEST = `# Fetch a 3D landmark tile at zoom 15 (Amsterdam Centraal area)
curl -H "TomTom-Api-Key: YOUR_API_KEY" \
     -H "TomTom-Api-Version: 2" \
  "https://api.tomtom.com/maps/orbis/display/3d/landmarks/tile/15/16763/10868?apiVersion=2&key=YOUR_API_KEY" \
  --output landmarks_z15.glb

# Zoom 16 — higher detail
curl -H "TomTom-Api-Key: YOUR_API_KEY" \
     -H "TomTom-Api-Version: 2" \
  "https://api.tomtom.com/maps/orbis/display/3d/landmarks/tile/16/33526/21736?apiVersion=2&key=YOUR_API_KEY" \
  --output landmarks_z16.glb`;

const CODE_RESPONSE = `HTTP/1.1 200 OK
Content-Type: model/gltf-binary
Cache-Control: max-age=86400
ETag: W/"2fdbd61f30456"
Tracking-ID: AbCd1234EfGh5678

<binary glTF 2.0 data — 3D landmark models for the tile area>

# 204 No Content is returned when there are no 3D landmarks in the requested tile area.
# This is valid — absence of data does not indicate an error.`;

const CODE_TILE_COORDS = `// Convert lat/lng to 3D landmark tile coordinates
function latLngToTile(lat, lng, zoom) {
  const x = Math.floor((lng + 180) / 360 * Math.pow(2, zoom));
  const latRad = lat * Math.PI / 180;
  const y = Math.floor((1 - Math.log(Math.tan(latRad) + 1 / Math.cos(latRad)) / Math.PI) / 2 * Math.pow(2, zoom));
  return { x, y, zoom };
}

// 3D landmarks are only available at zoom 15 and 16
const LANDMARK_ZOOMS = [15, 16];

function getLandmarkTileUrl(lat, lng, zoom, apiKey) {
  if (!LANDMARK_ZOOMS.includes(zoom)) {
    throw new Error(\`3D landmark tiles only available at zoom 15 or 16, got \${zoom}\`);
  }
  const { x, y } = latLngToTile(lat, lng, zoom);
  return \`https://api.tomtom.com/maps/orbis/display/3d/landmarks/tile/\${zoom}/\${x}/\${y}?key=\${apiKey}&apiVersion=2\`;
}

// Example: Eiffel Tower area at zoom 15
const url = getLandmarkTileUrl(48.8584, 2.2945, 15, 'YOUR_API_KEY');
console.log(url);`;

const CODE_THREEJS = `import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
import { MeshoptDecoder } from 'three/examples/jsm/libs/meshopt_decoder.module';
import { KTX2Loader } from 'three/examples/jsm/loaders/KTX2Loader';

const API_KEY = 'YOUR_API_KEY';

// The tile is compressed using EXT_meshopt_compression and KHR_texture_basisu.
// Both decoders must be provided to the GLTFLoader.
const loader = new GLTFLoader();
loader.setMeshoptDecoder(MeshoptDecoder);

const ktx2Loader = new KTX2Loader()
  .setTranscoderPath('/basis/')
  .detectSupport(renderer);
loader.setKTX2Loader(ktx2Loader);

// Tile coordinates: zoom 15, Amsterdam area
const tileUrl = \`https://api.tomtom.com/maps/orbis/display/3d/landmarks/tile/15/16763/10868?key=\${API_KEY}&apiVersion=2\`;

loader.load(tileUrl, (gltf) => {
  // Tile is georeferenced in EPSG:3857 — vertices are in real-world metres.
  // Z-axis = altitude (not Y-axis as glTF normally assumes).
  const model = gltf.scene;
  scene.add(model);
});`;

/* ─── Page ───────────────────────────────────────────────────────────────────── */
export default function Map3dLandmarks({ onNavigate }) {
  return (
    <div className="page page--wide">
      <div className="page-header page-header--with-tabs">
        <h1>3D Landmarks Tile</h1>
        <PageActions />
        <VersionTabBar versions={['v3']} activeTab="v3" onTabChange={() => {}} />
      </div>
      <PrivatePreviewBanner api="Map Display API v3 (Orbis Maps)" />
      <ApiRefTwoCol
        description="Binary glTF 2.0 (GLB) tiles containing 3D models of buildings and landmarks. Available at zoom levels 15 and 16 only. Tiles are georeferenced in EPSG:3857, compressed using EXT_meshopt_compression and KHR_texture_basisu extensions."
        sections={[
          {
            id: 'request',
            heading: 'Request',
            method: 'GET',
            note: 'https://api.tomtom.com/maps/orbis/display/3d/landmarks/tile/{zoom}/{x}/{y}?key={Your_API_Key}&apiVersion=2',
            params: PARAMS_REQUEST,
            code: CODE_REQUEST,
            lang: 'bash',
          },
          {
            id: 'headers',
            heading: 'Request headers',
            params: PARAMS_HEADERS,
            code: `# Recommended: authenticate via header (more secure than query param)
curl -H "TomTom-Api-Key: YOUR_API_KEY" \\
     -H "TomTom-Api-Version: 2" \\
     -H "If-None-Match: W/\\"2fdbd61f30456\\"" \\
  "https://api.tomtom.com/maps/orbis/display/3d/landmarks/tile/15/16763/10868"`,
            lang: 'bash',
          },
          {
            id: 'response',
            heading: 'Response',
            params: PARAMS_RESPONSE,
            code: CODE_RESPONSE,
            lang: 'bash',
          },
          {
            id: 'tile-coords',
            heading: 'Tile coordinate calculation',
            params: [],
            code: CODE_TILE_COORDS,
            lang: 'javascript',
          },
          {
            id: 'threejs',
            heading: 'Three.js integration',
            params: [],
            code: CODE_THREEJS,
            lang: 'javascript',
          },
        ]}
      />
    </div>
  );
}
