import ApiRefTwoCol from '../components/ui/ApiRefTwoCol';
import PageActions from '../components/ui/PageActions';
import PrivatePreviewBanner from '../components/ui/PrivatePreviewBanner';
import VersionTabBar from '../components/ui/VersionTabBar';

/* ─── Parameters ─────────────────────────────────────────────────────────────── */
const PARAMS_REQUEST = [
  { name: 'zoom', required: true, type: 'integer (path)', desc: 'Zoom level of the extended tile. Available zoom levels: 0–11, 12, and 14. Zoom 13 and 15–22 are not supported and return HTTP 400.' },
  { name: 'x', required: true, type: 'integer (path)', desc: 'Tile column index on the zoom grid. Valid range: 0 to 2^zoom − 1.' },
  { name: 'y', required: true, type: 'integer (path)', desc: 'Tile row index on the zoom grid. Valid range: 0 to 2^zoom − 1.' },
  { name: 'apiVersion', required: true, type: 'string (query)', values: ['2'], desc: 'API version to call. Must be 2. Overrides the TomTom-Api-Version header if set.' },
  { name: 'key', required: true, type: 'string (query)', desc: 'Your TomTom API key. Alternatively, pass as TomTom-Api-Key request header for improved security.' },
  { name: 'geopoliticalView', type: 'string (query)', default: 'auto (by request origin)', values: ['Unified', 'IN', 'PK', 'AR', 'Arabic', 'KR', 'RS', 'MY', 'CL', 'DZ', 'PH', 'BN', 'TW', 'MA', 'TR', 'IL', 'VN', 'US'], desc: 'Geopolitical view for disputed territories and borders. Defaults to the view appropriate for the country of the request origin.' },
];

const PARAMS_HEADERS = [
  { name: 'TomTom-Api-Key', required: true, type: 'string (header)', desc: 'Preferred authentication method. Recommended over the key query parameter for improved security.' },
  { name: 'TomTom-Api-Version', required: true, type: 'integer (header)', desc: 'API version. Current value: 2.' },
  { name: 'Accept', type: 'string (header)', values: ['application/vnd.mapbox-vector-tile'], desc: 'Content type accepted. Falls back to default if not supported.' },
  { name: 'Accept-Encoding', type: 'string (header)', values: ['gzip', 'br'], desc: 'Accepted content encoding. Use gzip or br for compressed responses.' },
  { name: 'If-None-Match', type: 'string (header)', desc: 'Conditional request. Returns 304 Not Modified if the tile ETag matches — avoids re-downloading unchanged tiles.' },
  { name: 'Tracking-ID', type: 'string (header)', desc: 'Optional request trace identifier. Must match ^[a-zA-Z0-9-]{1,100}. Replicated in the response if provided.' },
];

const PARAMS_RESPONSE = [
  { name: 'body', type: 'binary (application/vnd.mapbox-vector-tile)', desc: 'Gzip or Brotli compressed Mapbox Vector Tile (MVT) in Protocol Buffer format. Contains data for one or more regular tiles. Use the Extended Tiles Toolkit to clip and convert to standard tiles.' },
  { name: 'Content-Type', type: 'response header', desc: 'application/vnd.mapbox-vector-tile' },
  { name: 'Content-Encoding', type: 'response header', desc: 'gzip or br — tiles are compressed. Most HTTP clients decompress automatically.' },
  { name: 'Cache-Control', type: 'response header', desc: 'Tiles are publicly cacheable. Respect max-age to minimise API calls.' },
  { name: 'ETag', type: 'response header', desc: 'Entity tag for conditional requests. Example: W/"2fdbd61f30456".' },
  { name: 'Tracking-ID', type: 'response header', desc: 'Replicated from the request Tracking-ID header, or auto-generated by the service.' },
];

/* ─── Code examples ──────────────────────────────────────────────────────────── */
const CODE_REQUEST = `# Fetch an extended tile at zoom 12 (covers regular zoom 12 and 13)
curl -H "TomTom-Api-Key: YOUR_API_KEY" \
     -H "TomTom-Api-Version: 2" \
     -H "Accept-Encoding: gzip" \
  "https://api.tomtom.com/maps/orbis/display/extended/tile/12/2094/1362?apiVersion=2&key=YOUR_API_KEY" \
  --output extended_z12.pbf

# Fetch an extended tile at zoom 14 (covers regular zoom 14–22)
curl -H "TomTom-Api-Key: YOUR_API_KEY" \
     -H "TomTom-Api-Version: 2" \
     -H "Accept-Encoding: gzip" \
  "https://api.tomtom.com/maps/orbis/display/extended/tile/14/8376/5452?apiVersion=2&key=YOUR_API_KEY" \
  --output extended_z14.pbf`;

const CODE_RESPONSE = `HTTP/1.1 200 OK
Content-Type: application/vnd.mapbox-vector-tile
Content-Encoding: gzip
Cache-Control: max-age=86400
ETag: W/"2fdbd61f30456"
Tracking-ID: AbCd1234EfGh5678

<gzip-compressed Protocol Buffer data>
# Contains vector tile layers with data for multiple regular zoom levels.
# Use the Extended Tiles Toolkit to clip/filter/scale to individual tile coordinates.`;

const CODE_TOOLKIT = `// Using the Extended Tiles Toolkit to extract a regular tile from an extended tile
import { ExtendedTilesToolkit } from '@tomtom-international/extended-tiles-toolkit';

const API_KEY = 'YOUR_API_KEY';

// Fetch extended tile at zoom 14 — covers all regular zoom levels 14–22
async function fetchExtendedTile(extZoom, x, y) {
  const url = \`https://api.tomtom.com/maps/orbis/display/extended/tile/\${extZoom}/\${x}/\${y}?apiVersion=2&key=\${API_KEY}\`;
  const response = await fetch(url, {
    headers: {
      'TomTom-Api-Key': API_KEY,
      'TomTom-Api-Version': '2',
      'Accept-Encoding': 'gzip',
    },
  });
  return response.arrayBuffer();
}

// Convert extended tile to a regular tile at a specific target zoom
async function getRegularTile(targetZoom, targetX, targetY) {
  const toolkit = new ExtendedTilesToolkit();

  // Determine the extended tile coordinate that covers the target tile
  const extCoord = toolkit.getExtendedTileCoord(targetZoom, targetX, targetY);

  const extendedTileData = await fetchExtendedTile(
    extCoord.zoom,
    extCoord.x,
    extCoord.y
  );

  // Clip, filter and scale to produce the regular tile
  return toolkit.extractRegularTile(extendedTileData, targetZoom, targetX, targetY);
}

// Example: get a regular z18 tile by extracting from the covering z14 extended tile
const regularTile = await getRegularTile(18, 134024, 87248);`;

const CODE_GEOPOLITICAL = `// Fetch extended tiles with a specific geopolitical view
const API_KEY = 'YOUR_API_KEY';

function buildExtendedTileUrl(zoom, x, y, view) {
  const params = new URLSearchParams({
    apiVersion: '2',
    key: API_KEY,
    ...(view && { geopoliticalView: view }),
  });
  return \`https://api.tomtom.com/maps/orbis/display/extended/tile/\${zoom}/\${x}/\${y}?\${params}\`;
}

// Indian geopolitical view (shows India's territorial claims)
const indiaViewUrl = buildExtendedTileUrl(12, 2798, 1622, 'IN');

// Unified international view
const unifiedUrl = buildExtendedTileUrl(12, 2798, 1622, 'Unified');`;

/* ─── Page ───────────────────────────────────────────────────────────────────── */
export default function MapExtendedTiles({ onNavigate }) {
  return (
    <div className="page page--wide">
      <div className="page-header page-header--with-tabs">
        <h1>Extended Tiles</h1>
        <PageActions />
        <VersionTabBar versions={['v3']} activeTab="v3" onTabChange={() => {}} />
      </div>
      <PrivatePreviewBanner api="Map Display API v3 (Orbis Maps)" />
      <ApiRefTwoCol
        description="Extended vector content tiles that pack data for multiple regular tile zoom levels into a single request. Reduces request count, bandwidth, and improves cache efficiency. Requires the Extended Tiles Toolkit to clip and convert to regular MVT tiles. Available at zoom levels 0–11, 12, and 14 only."
        sections={[
        {
          id: 'request',
          heading: 'Request',
          method: 'GET',
          note: 'https://api.tomtom.com/maps/orbis/display/extended/tile/{zoom}/{x}/{y}?apiVersion=2&key={Your_API_Key}',
          params: PARAMS_REQUEST,
          code: CODE_REQUEST,
          lang: 'bash',
        },
        {
          id: 'headers',
          heading: 'Request headers',
          params: PARAMS_HEADERS,
          code: `# Recommended: authenticate via header
curl -H "TomTom-Api-Key: YOUR_API_KEY" \\
     -H "TomTom-Api-Version: 2" \\
     -H "Accept-Encoding: gzip" \\
     -H "If-None-Match: W/\\"2fdbd61f30456\\"" \\
  "https://api.tomtom.com/maps/orbis/display/extended/tile/14/8376/5452"`,
          lang: 'bash',
        },
        {
          id: 'zoom-levels',
          heading: 'Extended zoom level mapping',
          note: 'Each extended zoom level covers one or more regular tile zoom levels. Zoom levels 13 and 15–22 are not supported.',
          params: [
            { name: 'Extended zoom 0–11', type: 'zoom mapping', desc: 'Covers the same regular zoom level (1:1 mapping).' },
            { name: 'Extended zoom 12', type: 'zoom mapping', desc: 'Covers regular zoom levels 12 and 13.' },
            { name: 'Extended zoom 13', type: 'zoom mapping', desc: 'Not supported — returns HTTP 400.' },
            { name: 'Extended zoom 14', type: 'zoom mapping', desc: 'Covers regular zoom levels 14 through 22.' },
            { name: 'Extended zoom 15–22', type: 'zoom mapping', desc: 'Not supported — returns HTTP 400.' },
          ],
          code: `# Supported extended zoom levels: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14
# Unsupported: 13, 15, 16, 17, 18, 19, 20, 21, 22 → returns HTTP 400

# z12 extended tile → produces regular z12 and z13 tiles
# z14 extended tile → produces regular z14 through z22 tiles`,
          lang: 'bash',
        },
        {
          id: 'response',
          heading: 'Response',
          params: PARAMS_RESPONSE,
          code: CODE_RESPONSE,
          lang: 'bash',
        },
        {
          id: 'toolkit',
          heading: 'Extended Tiles Toolkit',
          params: [],
          code: CODE_TOOLKIT,
          lang: 'javascript',
        },
        {
          id: 'geopolitical',
          heading: 'Geopolitical view',
          params: [],
          code: CODE_GEOPOLITICAL,
          lang: 'javascript',
        },
      ]}
      />
    </div>
  );
}
